### PR TITLE
Fix/updated date

### LINKED ISSUE #37: Add "data last updated" date
the legend should indicate the date last updated.

# Tasks

- [x] allow retrieving the last updated date from API or static file (backend)
- [ ] fetch the last updated date from the backend, display in the legend
- [ ] use the last updated date as a reference point for date shortcuts (last 7 days, last 30 days, etc.)

### PR DESCRIPTION
**Pull request by touchRED**
Fixes #37

### CODE REVIEW

**Review by Lane — CHANGES_REQUESTED** [review]
@touchRED looking good so far, some changes:

- seeing " 2021 (DAY: 2))" for the end date next to the "SUMMARY" heading when selecting a "last `x` days" option

image

- would also like to test and make sure the date pickers have the proper date range set, but the pickers are not in this PR.  can you resync?

**Comment by touchRED** [comment]
@Lane thanks for the catch! should be good to go

**Comment by Lane** [comment]
thanks! with the date pickers, we should not allow invalid selections.  can you add the following:

- do not allow selection of dates outside of the valid date range
- do not allow specifying a start date that is equal or after the end date
- do not allow specifying an end date that is equal to or befor the start date

**Comment by touchRED** [comment]
@Lane got it 👍

**Comment by Lane** [comment]
@touchRED awesome, looks great, thank you!

**Pull request merged**
